services:
  mariadb:
    image: mariadb:11
    container_name: webcore_db
    restart: always
    environment:
      MARIADB_DATABASE: webcore_db
      MARIADB_USER: webcore
      MARIADB_PASSWORD: webcore123
      MARIADB_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uwebcore", "-pwebcore123"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: webcore_app
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/webcore_db
      SPRING_DATASOURCE_USERNAME: webcore
      SPRING_DATASOURCE_PASSWORD: webcore123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  mariadb_data:
